const mongoose = require("mongoose");

const Policy2Schema = new mongoose.Schema({
   
    //po1
    OverviewPolicyName1: { type: String, default: "" },
    agent_scan_mode1: { type: String, default: 'Smart Scan' },
    files_to_Scan1: { type: String, default: 'All Scanable files' },
    scan_hidden_folders1: { type: String, default: 'Enabled' },
    scan_compressed_files1: { type: String, default: '3' },
    scan_ole_object1: { type: String, default: '3' },
    detect_exploit_code1: { type: String, default: 'Enabled' },
    virus_scan_settings_only1: { type: String, default: 'Enabled' },
    cpu_usage1: { type: String, default: 'Medium' },

    //po1
    tab8: { type: String, default: "images/tab1.png" },
    tab9: { type: String, default: "images/tab1.png" },
    tab10: { type: String, default: "images/tab1.png" },
    tab11: { type: String, default: "images/tab1.png" },
    tab12: { type: String, default: "images/tab1.png" },
    tab13: { type: String, default: "images/tab1.png" },
    tab14: { type: String, default: "images/tab1.png" },
    tab15: { type: String, default: "images/tab1.png" },

    //MCA
    use_activeAction1Policy2: { type: String, default: "" },
    customize_action_for_porbable_virus_checkbox1: { type: String, default: "" },
    customize_action_for_porbable_virus_option1: { type: String, default: "Quarantine" },
    first_action1: { type: String, default: "Quarantine" },
    second_action1: { type: String, default: "Quarantine" },
    joke1: { type: String, default: "Quarantine" },
    trojans1: { type: String, default: "Quarantine" },
    virus11: { type: String, default: "Quarantine" },
    virus21: { type: String, default: "Quarantine" },
    test_virus1: { type: String, default: "Quarantine" },
    packer1: { type: String, default: "Quarantine" },
    probable_malware11: { type: String, default: "Quarantine" },
    probable_malware21: { type: String, default: "Quarantine" },
    back_up_files1: { type: String, default: "Enabled" },
    damage_cleanup_services11: { type: String, default: "Enabled" },
    damage_cleanup_services21: { type: String, default: "Advanced clean-up" },
    run_cleanup1: { type: String, default: "Enabled" },
    apex_one_terminates_processes1: { type: String, default: "Clean" },

    tab16: { type: String, default: "images/tab1.png" },
    tab17: { type: String, default: "images/tab1.png" },
    tab18: { type: String, default: "images/tab1.png" },
    tab19: { type: String, default: "images/tab1.png" },
    tab20: { type: String, default: "images/tab1.png" },


    //2.Real-Time Scan Policy Settings - 21 -32

    virus_scan2: { type: String, default: 'Enabled' },
    spyware_scan2: { type: String, default: 'Enabled' },
    user_activity_on_files2: { type: String, default: 'created/modified and retrieved' },
    files_to_scan2: { type: String, default: 'All Scanable files' },
    scan_network_drive2: { type: String, default: 'Enabled' },
    enable12: { type: String, default: 'Enabled' },
    enable22: { type: String, default: 'Enabled' },
    enable32: { type: String, default: 'Enabled' },
    scan_compressed_files2: { type: String, default: '2' },
    scan_ole_objects2: { type: String, default: '3' },
    detect_exploit_code_in_ole_files2: { type: String, default: 'Enabled' },
    cvf_exploit_scanning2: { type: String, default: 'Enabled' },


    tab21: { type: String, default: "images/tab1.png" },
    tab22: { type: String, default: "images/tab1.png" },
    tab23: { type: String, default: "images/tab1.png" },
    tab24: { type: String, default: "images/tab1.png" },
    tab25: { type: String, default: "images/tab1.png" },
    tab26: { type: String, default: "images/tab1.png" },
    tab27: { type: String, default: "images/tab1.png" },
    tab28: { type: String, default: "images/tab1.png" },
    tab29: { type: String, default: "images/tab1.png" },
    tab30: { type: String, default: "images/tab1.png" },
    tab31: { type: String, default: "images/tab1.png" },
    tab32: { type: String, default: "images/tab1.png" },


    //Real-Time Scan-Action Settings

    use_activeAction2Policy2: { type: String, default: "yes3" },
    customize_action_for_porbable_virus_checkbox2: { type: String, default: "" },
    customize_action_for_porbable_virus_option2: { type: String, default: "Quarantine" },
    first_action2: { type: String, default: "Quarantine" },
    second_action2: { type: String, default: "Quarantine" },
    joke2: { type: String, default: "Quarantine" },
    trojans2: { type: String, default: "Quarantine" },
    virus12: { type: String, default: "Quarantine" },
    virus22: { type: String, default: "Quarantine" },
    test_virus2: { type: String, default: "Quarantine" },
    packer2: { type: String, default: "Quarantine" },
    probable_malware12: { type: String, default: "Quarantine" },
    probable_malware22: { type: String, default: "Quarantine" },
    back_up_files2: { type: String, default: "Enabled" },
    run_cleanup2: { type: String, default: 'Enabled' },
    apex_one_terminates_processes2: { type: String, default: "Clean" },

    //Real-Time Scan-Action Settings 33 - 36 - img

    tab33: { type: String, default: "images/tab1.png" },
    tab34: { type: String, default: "images/tab1.png" },
    tab35: { type: String, default: "images/tab1.png" },
    tab36: { type: String, default: "images/tab1.png" },


    //3 Schedule Scan Policy Settings - 37-45
    virus_scan3: { type: String, default: 'Enabled' },
    spyware_scan3: { type: String, default: 'Enabled' },
    configure_schedule_scan_checkbox3Policy2: { type: String, default: "" },
    configure_schedule_scan_weekevery3: { type: String, default: "" },
    configure_schedule_scan_month3: { type: String, default: "" },
    configure_schedule_scan_date3: { type: String, default: "" },
    configure_schedule_scan_day3: { type: String, default: "" },
    configure_schedule_scan_time3: { type: String, default: "" },
    filestoscan3: { type: String, default: "All Scanable files" },
    scan_compressed_files3: { type: String, default: "2" },
    scanoleobjects3: { type: String, default: "3" },
    detect_exploit_code3: { type: String, default: "Enabled" },
    scan_boot_area3: { type: String, default: "Enabled" },
    cpu_usage3: { type: String, default: 'Medium' },

    tab37: { type: String, default: "images/tab1.png" },
    tab38: { type: String, default: "images/tab1.png" },
    tab39: { type: String, default: "images/tab1.png" },
    tab40: { type: String, default: "images/tab1.png" },
    tab41: { type: String, default: "images/tab1.png" },
    tab42: { type: String, default: "images/tab1.png" },
    tab43: { type: String, default: "images/tab1.png" },
    tab44: { type: String, default: "images/tab1.png" },
    tab45: { type: String, default: "images/tab1.png" },

    //3Schedule Scan-Action Settings 
    use_activeAction3Policy2: { type: String, default: "yes3" },
    customize_action_for_porbable_virus_checkbox3: { type: String, default: "" },
    customize_action_for_porbable_virus_option3: { type: String, default: "Quarantine" },
    first_action3: { type: String, default: "Quarantine" },
    second_action3: { type: String, default: "Quarantine" },
    joke3: { type: String, default: "Quarantine" },
    trojans3: { type: String, default: "Quarantine" },
    virus13: { type: String, default: "Quarantine" },
    virus23: { type: String, default: "Quarantine" },
    test_virus3: { type: String, default: "Quarantine" },
    packer3: { type: String, default: "Quarantine" },
    probable_malware13: { type: String, default: "Quarantine" },
    probable_malware23: { type: String, default: "Quarantine" },
    back_up_files3: { type: String, default: "Enabled" },
    damage_cleanup_services13: { type: String, default: "Enabled" },
    damage_cleanup_services23: { type: String, default: "Advanced clean-up" },
    run_cleanup3: { type: String, default: "Enabled" },
    apex_one_terminates_processes3: { type: String, default: "Clean" },

    // 46 - 50
    tab46: { type: String, default: "images/tab1.png" },
    tab47: { type: String, default: "images/tab1.png" },
    tab48: { type: String, default: "images/tab1.png" },
    tab49: { type: String, default: "images/tab1.png" },
    tab50: { type: String, default: "images/tab1.png" },


    bm: { type: String, default: 'Enabled with' },
    bm1: { type: String, default: 'Enabled' },
    bm2: { type: String, default: 'Enabled' },
    bm3: { type: String, default: 'Enabled' },
    bm4: { type: String, default: 'Enabled' },
    bm5: { type: String, default: 'Enabled' },
    bm6: { type: String, default: 'Enabled' },
    bm7: { type: String, default: 'Enabled' },
    predictiveMl: { type: String, default: 'Enabled' },
    suspicious_Connection: { type: String, default: 'Enabled' },
    vulnerability_protection: { type: String, default: 'Enabled' },
    device_control: { type: String, default: 'Enabled' },
    web_reputation1: { type: String, default: 'Enabled' },
    web_reputation2: { type: String, default: 'Medium' },
    application_control: { type: String, default: 'Enabled' },
    firewall: { type: String, default: 'Enabled' },
    agent_self_protection: { type: String, default: 'Enabled' },
    agent_unload_unlock: { type: String, default: 'Configured' },
    agent_uninstallation: { type: String, default: 'Configured' },
    additional_service1: { type: String, default: 'Enabled' },
    additional_service2: { type: String, default: 'Enabled' },
    additional_service3: { type: String, default: 'Enabled' },
    additional_service4: { type: String, default: 'Enabled' },
    additional_service5: { type: String, default: 'Enabled' },
    additional_service6: { type: String, default: 'Enabled' },
    additional_service7: { type: String, default: 'Enabled' },
    additional_service8: { type: String, default: 'Enabled' },
    additional_service9: { type: String, default: 'Enabled' },
    additional_service10: { type: String, default: 'Enabled' },

    tab51: { type: String, default: "images/tab1.png" },
    tab51BM1: { type: String, default: "images/tab1.png" },
    tab51BM2: { type: String, default: "images/tab1.png" },
    tab51BM3: { type: String, default: "images/tab1.png" },
    tab51BM4: { type: String, default: "images/tab1.png" },
    tab51BM5: { type: String, default: "images/tab1.png" },
    tab51BM6: { type: String, default: "images/tab1.png" },
    tab51BM7: { type: String, default: "images/tab1.png" },
    
    tab52: { type: String, default: "images/tab1.png" },
    tab53: { type: String, default: "images/tab1.png" },
    tab54: { type: String, default: "images/tab1.png" },
    tab55: { type: String, default: "images/tab1.png" },
    tab56: { type: String, default: "images/tab1.png" },
    tab59: { type: String, default: "images/tab1.png" },
    tabVP: { type: String, default: "images/tab1.png" },
    tabDC: { type: String, default: "images/tab1.png" },
    tabAC: { type: String, default: "images/tab1.png" },

});

module.exports = new mongoose.model("PolicyOverview2", Policy2Schema);


